<a href="https://colab.research.google.com/github/GunelXelilli/Vendor-Analysis/blob/main/Vendorsql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
conn = sqlite3.connect('my_database.db')

In [ ]:
vendors=pd.read_csv('/content/vendors_cleaned_pg.csv')
sales = pd.read_csv('/content/sales_cleaned_cleaned_pg.csv')
inventory = pd.read_csv('/content/merged_inventory_cleaned_cleaned_pg.csv')
vendor_invoice = pd.read_csv('/content/vendor_invoice_cleaned_cleaned_pg.csv')
vendor_sales = pd.read_csv('/content/vendor_sales_summary_cleaned_cleaned_pg.csv')
purchases = pd.read_csv('/content/purchases_cleaned_cleaned_pg.csv')
purchase_prices = pd.read_csv('/content/purchase_prices_cleaned_cleaned_pg.csv')

In [ ]:
vendors.to_sql('vendors',conn,index=False,if_exists='replace')

132

In [ ]:
pd.read_sql("Select * from vendors limit 5",conn)

   VendorNumber                     VendorName
0             2  Ira Goldman And Williams, Llp
1            54    Aaper Alcohol & Chemical Co
2            60        Adamba Imports Intl Inc
3           105             Altamar Brands Llc
4           200      American Spirits Exchange

In [ ]:
sales.to_sql('sales', conn, index=False, if_exists='replace')

3422356

In [ ]:
pd.read_sql("SELECT * FROM sales LIMIT 5", conn)

,InventoryId,Store,Brand,Description,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Classification,ExciseTax,VendorNo,VendorName,ABC,CohortMonth,OrderMonth,CohortIndex
0,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,16.49,16.49,2024-01-01,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
1,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,2.0,32.98,16.49,2024-01-02,1.0,1.57,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
2,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,16.49,16.49,2024-01-03,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
3,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,14.49,14.49,2024-01-08,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
4,1_HARDERSFIELD_1005,1.0,1005.0,Makers Mark Combo Pack,2.0,69.98,34.99,2024-01-09,1.0,0.79,12546.0,Jim Beam Brands Company,B,2024-01-01,2024-01-01,0.0

In [ ]:
inventory.to_sql('inventory', conn, index=False, if_exists='replace')

202858

In [ ]:
pd.read_sql("SELECT * FROM sales LIMIT 5",conn)

,InventoryId,Store,Brand,Description,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Classification,ExciseTax,VendorNo,VendorName,ABC,CohortMonth,OrderMonth,CohortIndex
0,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,16.49,16.49,2024-01-01,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
1,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,2.0,32.98,16.49,2024-01-02,1.0,1.57,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
2,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,16.49,16.49,2024-01-03,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
3,1_HARDERSFIELD_1004,1.0,1004.0,Jim Beam w/2 Rocks Glasses,1.0,14.49,14.49,2024-01-08,1.0,0.79,12546.0,Jim Beam Brands Company,C,2024-01-01,2024-01-01,0.0
4,1_HARDERSFIELD_1005,1.0,1005.0,Makers Mark Combo Pack,2.0,69.98,34.99,2024-01-09,1.0,0.79,12546.0,Jim Beam Brands Company,B,2024-01-01,2024-01-01,0.0

In [ ]:
vendor_invoice.to_sql('vendor_invoice', conn, index=False, if_exists='replace')

5543

In [ ]:
pd.read_sql("Select * from vendor_invoice limit 5",conn)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight
0,105,Altamar Brands Llc,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47
1,4466,American Vintage Beverage,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57
2,388,Atlantic Importing Company,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61
3,480,Bacardi Usa Inc,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20
4,516,Banfi Products Corp,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20

In [ ]:
vendor_sales.to_sql('vendor_sales',conn,index=False,if_exists='replace')

10514

In [ ]:
pd.read_sql("Select * from vendor_sales limit 5",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,Brown-Forman Corp,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,672819.31,5101919.51,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,Martignetti Companies,3405,Titos Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,561512.37,4819073.49,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,Pernod Ricard Usa,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,461140.15,4538120.60,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,Diageo North America Inc,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,420050.01,4475972.88,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,Diageo North America Inc,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,545778.28,4223107.62,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [ ]:
purchases.to_sql('purchases',conn,index=False,if_exists='replace')

2372474

In [ ]:
pd.read_sql("Select * from purchases limit 5",conn)

,InventoryId,Store,Brand,VendorNumber,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,105,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,4466,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,4466,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,4466,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,388,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [ ]:
purchase_prices.to_sql('purchase_prices',conn,index=False,if_exists='replace')

12256

In [ ]:
pd.read_sql("Select * from purchase_prices limit 5",conn)

,Brand,Description,Price,Volume,Classification,PurchasePrice,VendorNumber,VendorName,Size_value,Size_unit,Pack_num,Total_volume_ml,Price_per_ml
0,58,Gekkeikan Black & Gold Sake,12.99,750.0,1,9.28,8320,Shaw Ross Int L Imp Ltd,750.0,ml,1,750.0,0.012373
1,62,Herradura Silver Tequila,36.99,750.0,1,28.67,1128,Brown-Forman Corp,750.0,ml,1,750.0,0.038227
2,63,Herradura Reposado Tequila,38.99,750.0,1,30.46,1128,Brown-Forman Corp,750.0,ml,1,750.0,0.040613
3,72,No. 3 London Dry Gin,34.99,750.0,1,26.11,9165,Ultra Beverage Company Llp,750.0,ml,1,750.0,0.034813
4,75,Three Olives Tomato Vodka,14.99,750.0,1,10.94,7245,Proximo Spirits Inc.,750.0,ml,1,750.0,0.014587

Vendor/Sales Analysis with sql

In [ ]:
#En cox satis eden vendorlar
query="""
Select VendorNo,VendorName,sum(SalesDollars) from sales
group by VendorNo,VendorName
order by sum(SalesDollars) desc
limit 5
"""
pd.read_sql(query,conn)

   VendorNo                VendorName  sum(SalesDollars)
0    3960.0  Diageo North America Inc       1.632492e+07
1    4425.0     Martignetti Companies       9.486040e+06
2   12546.0   Jim Beam Brands Company       8.333135e+06
3   17035.0         Pernod Ricard Usa       7.701517e+06
4    1392.0  Constellation Brands Inc       6.089980e+06

In [ ]:
# Hansi vendorların satisi yoxdur?
query = """
SELECT v.VendorNumber, v.VendorName
FROM vendors v
LEFT JOIN sales s
ON v.VendorNumber = s.VendorNo
WHERE s.VendorNo IS NULL
"""

pd.read_sql(query, conn)

    VendorNumber                   VendorName
0             54  Aaper Alcohol & Chemical Co
1            200    American Spirits Exchange
2           2973             Flemish Lion Llc
3           3551  Gilmanton Winery & Vineyard
4           3670              Halo Distillery
5           4901          Laureate Imports Co
6           5083             Loyal Dog Winery
7           6280                     Uncorked
8           9099                 Truett Hurst
9          90059         Black Cove Beverages
10         99166        Stark Brewing Company
11        201359           Flavor Essence Inc
12             0                      Unknown

In [ ]:
#Hansi vendorlarin umumi satis meblegi en yuksekdir
query="""
SELECT VendorName, TotalSalesDollars
FROM vendor_sales
ORDER BY TotalSalesDollars DESC
LIMIT 5;
"""
pd.read_sql(query,conn)

                 VendorName  TotalSalesDollars
0         Brown-Forman Corp         5101919.51
1     Martignetti Companies         4819073.49
2         Pernod Ricard Usa         4538120.60
3  Diageo North America Inc         4475972.88
4  Diageo North America Inc         4223107.62

In [ ]:
#Hər vendorun satış payını ümumi satışa görə hesablayaq.
query="""
SELECT  vs.VendorName,vs.TotalSalesDollars,vs.TotalSalesDollars * 1.0 / SUM(vs.TotalSalesDollars) OVER () AS Sales_Share
FROM vendor_sales vs
ORDER BY Sales_Share DESC
LIMIT 10;
"""
pd.read_sql(query,conn)

                 VendorName  TotalSalesDollars  Sales_Share
0         Brown-Forman Corp         5101919.51     0.011297
1     Martignetti Companies         4819073.49     0.010671
2         Pernod Ricard Usa         4538120.60     0.010049
3  Diageo North America Inc         4475972.88     0.009911
4  Diageo North America Inc         4223107.62     0.009351
5           Bacardi Usa Inc         3383912.40     0.007493
6         Pernod Ricard Usa         2773367.73     0.006141
7  Diageo North America Inc         2640491.19     0.005847
8  Diageo North America Inc         2592041.35     0.005739
9   Jim Beam Brands Company         2435393.39     0.005393

In [ ]:
# Vendorları performance a görə kateqoriyalayaq
#bunun ucun en yuksek satisimiz,ve en az satisimizi oyrenek
query="""
Select max(SalesDollars),min(SalesDollars) from sales
"""
pd.read_sql(query,conn)
#gorunduyu kimi bu 5000000 dan coxdur
#indi ise min baxaq

   max(SalesDollars)  min(SalesDollars)
0           14487.24                0.0

In [ ]:
# Vendorları performance a görə kateqoriyalayaq
query="""
SELECT VendorNo,Performance,COUNT(*) AS SalesCount
FROM (
    SELECT VendorNo,
        CASE
            WHEN SalesDollars <= 1000 THEN 'Low'
            WHEN SalesDollars BETWEEN 1000 AND 10000 THEN 'Medium'
            ELSE 'High'
        END AS Performance
    FROM sales
) t
where Performance=="Medium"
GROUP BY VendorNo, Performance
"""
pd.read_sql(query,conn)

    VendorNo Performance  SalesCount
0      388.0      Medium           1
1      480.0      Medium         117
2      516.0      Medium           2
3      653.0      Medium           1
4     1128.0      Medium         158
5     1392.0      Medium           9
6     1485.0      Medium           9
7     1590.0      Medium           1
8     1601.0      Medium           1
9     1703.0      Medium           6
10    2000.0      Medium          17
11    2555.0      Medium           9
12    2561.0      Medium          15
13    3089.0      Medium           3
14    3252.0      Medium           9
15    3664.0      Medium           5
16    3924.0      Medium           1
17    3960.0      Medium         518
18    4425.0      Medium         155
19    4692.0      Medium           3
20    4848.0      Medium           1
21    6213.0      Medium           5
22    6785.0      Medium           1
23    7153.0      Medium           8
24    7239.0      Medium          32
25    7245.0      Medium           3
26    7749.0      Medium           1
27    8004.0      Medium           9
28    8112.0      Medium         149
29    8352.0      Medium           1
30    8664.0      Medium           5
31    8673.0      Medium           3
32    9165.0      Medium          45
33    9552.0      Medium          15
34    9744.0      Medium           7
35    9819.0      Medium           3
36   10000.0      Medium           5
37   10754.0      Medium          25
38   11567.0      Medium           3
39   12331.0      Medium           1
40   12546.0      Medium          40
41   17033.0      Medium           1
42   17035.0      Medium         170
43   90010.0      Medium           1
44   90024.0      Medium           1

In [ ]:
#Net Sales hesablayaq
query="""
Select VendorNumber,Vendorname,sum(TotalSalesDollars)-sum(TotalExcisetax) as Net_Sales
from vendor_sales
group by VendorNumber,VendorName
order by Net_Sales desc
"""
pd.read_sql(query,conn)

     VendorNumber                VendorName    Net_Sales
0            3960  Diageo North America Inc  64941351.62
1            4425     Martignetti Companies  40204157.11
2           17035         Pernod Ricard Usa  30780746.60
3           12546   Jim Beam Brands Company  29649726.70
4            1392  Constellation Brands Inc  23775124.97
..            ...                       ...          ...
121          6280                  Uncorked      1084.62
122         90026    Silver Mountain Ciders       337.67
123         90033   Fantasy Fine Wines Corp       323.08
124          1439    Capstone International       222.98
125          9099              Truett Hurst        14.88

[126 rows x 3 columns]

In [ ]:
#tranzaksiyalarin sayini tapaq her vendor ucun
query="""
SELECT VendorNumber,VendorName,COUNT(*) AS Number_of_Transactions
FROM vendor_sales
GROUP BY VendorNumber, VendorName
ORDER BY Number_of_Transactions DESC;
"""
pd.read_sql(query,conn)
#martignetti Companies tranzaksiya sayi coxdur

     VendorNumber                  VendorName  Number_of_Transactions
0            4425       Martignetti Companies                    1363
1            9552              M S Walker Inc                     818
2            9165  Ultra Beverage Company Llp                     815
3           10754              Perfecta Wines                     769
4            3252          E & J Gallo Winery                     500
..            ...                         ...                     ...
121         90026      Silver Mountain Ciders                       1
122         90033     Fantasy Fine Wines Corp                       1
123         90059        Black Cove Beverages                       1
124         99166       Stark Brewing Company                       1
125        201359          Flavor Essence Inc                       1

[126 rows x 3 columns]

In [ ]:
#satis trendine baxaq
query="""
SELECT strftime('%Y-%m', InvoiceDate) AS month,SUM(TotalSalesDollars) AS total_sales
FROM vendor_sales
join vendor_invoice using(VendorNumber)
GROUP BY strftime('%Y-%m', InvoiceDate)
ORDER BY month;
"""
pd.read_sql(query,conn)

      month   total_sales
0   2024-01  1.892405e+09
1   2024-02  2.080614e+09
2   2024-03  2.065851e+09
3   2024-04  2.107927e+09
4   2024-05  2.280026e+09
5   2024-06  2.107308e+09
6   2024-07  2.396234e+09
7   2024-08  2.123253e+09
8   2024-09  1.940746e+09
9   2024-10  2.466703e+09
10  2024-11  1.963421e+09
11  2024-12  2.032554e+09
12  2025-01  5.313867e+08

In [ ]:
#hansi Mehsullar daha cox satilib
query="""
SELECT InventoryId,SUM(SalesQuantity) AS Total_Quantity
FROM sales
GROUP BY InventoryId
ORDER BY Total_Quantity DESC
"""
pd.read_sql(query, conn)

                InventoryId  Total_Quantity
0           53_HILLFAR_8111          3624.0
1         34_PITMERDEN_4261          3597.0
2       20_BREDWARDINE_8111          3198.0
3         27_MOUNTMEND_8111          3172.0
4         27_MOUNTMEND_1892          2931.0
...                     ...             ...
206737     10_HORNSEY_11480             1.0
206738     10_HORNSEY_10731             1.0
206739     10_HORNSEY_10441             1.0
206740      10_HORNSEY_1006             1.0
206741      10_HORNSEY_1000             1.0

[206742 rows x 2 columns]

In [ ]:
#Top 20% məhsullar ümumi satışın neçə %-ni verir?
query="""
WITH ranked AS (
    SELECT InventoryId,SUM(SalesQuantity) AS Total_Quantity,RANK() OVER (ORDER BY SUM(SalesQuantity) DESC) AS rank,COUNT(*) OVER () AS total_products,
        SUM(SUM(SalesQuantity)) OVER (ORDER BY SUM(SalesQuantity) DESC) * 1.0 /
        SUM(SUM(SalesQuantity)) OVER () AS cumulative_pct #Top mehsullardan baslayaraq satislarimizi yigib onu umumi satisa boluruk
      FROM sales
    GROUP BY InventoryId
)
SELECT ROUND(MAX(cumulative_pct) * 100, 2) AS top_20_percent_sales
FROM ranked
WHERE rank <= total_products * 0.2;
"""
pd.read_sql(query,conn)
# balansli bir satis neticesi

   top_20_percent_sales
0                 71.48

 Preto analizi ile bu analiz göstərir ki, satışlar müəyyən qədər konsentrasiyalıdır, lakin tam dominant deyil. Yəni həm əsas məhsullar, həm də digər məhsullar birlikdə ümumi gəlirin formalaşmasında rol oynayır.

In [ ]:
query="""
SELECT
    ABC,
    SUM(SalesQuantity) AS total_sales
FROM sales
GROUP BY ABC;
"""
pd.read_sql(query,conn)

    ABC  total_sales
0  None          1.0
1     A    5635358.0
2     B    1649826.0
3     C     853911.0

Total=5,635,358+1,649,826+853,911+1≈8,139,096
5,635,358/8,139,096≈69.2%
1,649,826/8,139,096≈20.3%
853,911/8,139,096≈10.5%
bu A,B,C kategoriyalari mehsullarin satisdaki payidir

In [ ]:
#StockTurnover(stokun neçə dəfə satılıb yeniləndiyi) yuksek olan mehsullari cixaraq
query="""
SELECT Description,AVG(StockTurnover) AS Avg_StockTurnover
FROM vendor_sales
GROUP BY Description
ORDER BY Avg_StockTurnover DESC
LIMIT 5
"""
pd.read_sql(query,conn)

                    Description  Avg_StockTurnover
0  Pezzi King Svgn Bl Dry Creek         171.000000
1            DiSaronno Amaretto         171.000000
2       Beniotome Sesame Shochu         159.000000
3    Skinnygirl Tangerine Vodka         158.000000
4    Blue Chair Bay Coconut Rum         137.739397

In [ ]:
#Max
query="""
SELECT Description,MAX(StockTurnover) AS Max_StockTurnover
FROM vendor_sales
GROUP BY Description
ORDER BY Max_StockTurnover DESC
LIMIT 5
"""
pd.read_sql(query, conn)
#Buradan bunu anlayiriq ki məhsul bəzi dövrlərdə çox sürətli satılıb, amma stabil deyil

                    Description  Max_StockTurnover
0    Blue Chair Bay Coconut Rum              274.5
1  Pezzi King Svgn Bl Dry Creek              171.0
2            DiSaronno Amaretto              171.0
3       Beniotome Sesame Shochu              159.0
4    Skinnygirl Tangerine Vodka              158.0

In [ ]:
#Stokda olubda hec satilmayan mehsulum yoxdur
query="""
SELECT
    Description,
    StockTurnover
FROM vendor_sales
WHERE StockTurnover = 0
ORDER BY StockTurnover
"""
pd.read_sql(query,conn)

Empty DataFrame
Columns: [Description, StockTurnover]
Index: []

In [ ]:
#Hansi Vendorlar daha cox alib ama az satib
query="""
Select VendorNumber,VendorName,TotalSalesDollars,TotalPurchaseDollars
from vendor_sales
where TotalSalesDollars<TotalPurchaseDollars
group by VendorNumber
order by TotalPurchaseDollars desc
"""
pd.read_sql(query,conn)

,VendorNumber,VendorName,TotalSalesDollars,TotalPurchaseDollars
0,3960,Diageo North America Inc,176577.85,185784.10
1,4425,Martignetti Companies,119616.75,138369.42
2,6213,Mhw Ltd,130097.76,131392.96
3,1655,Fabrizia Spirits Llc,94406.84,96915.17
4,1128,Brown-Forman Corp,89296.41,93830.40
...,...,...,...,...
91,9099,Truett Hurst,14.99,236.64
92,1003,Bronco Wine Company,171.57,225.12
93,7749,R.P.Imports Inc,31.99,198.54
94,5612,Miltons Distributing Co,105.48,145.44
95,2396,Black Prince Distillery Inc,95.84,117.00

In [ ]:
#SalesToPurchaseRatio-(Satış/Alış nisbəti) rank edek Vendorlari ona gore
query="""
SELECT VendorNumber,VendorName,AVG(SalesToPurchaseRatio) AS Avg_Ratio,RANK() OVER (ORDER BY AVG(SalesToPurchaseRatio) DESC) AS Vendor_Rank
FROM vendor_sales
GROUP BY VendorNumber, VendorName
ORDER BY Avg_Ratio DESC;
"""
pd.read_sql(query,conn)
#AVG_Ratio 86.73 olanlarda satislar alislardan coxdur

     VendorNumber                   VendorName  Avg_Ratio  Vendor_Rank
0          201359           Flavor Essence Inc  86.730000            1
1            2555  Disaronno International Llc  22.262418            2
2            1703         Alisa Carr Beverages   7.146990            3
3            6213                      Mhw Ltd   6.525314            4
4            5455             Marsalle Company   4.880914            5
..            ...                          ...        ...          ...
121          6280                     Uncorked   0.512416          122
122          5083             Loyal Dog Winery   0.478826          123
123         90059         Black Cove Beverages   0.432551          124
124          1587          Vineyard Brands Llc   0.384433          125
125          9099                 Truett Hurst   0.063345          126

[126 rows x 4 columns]

In [ ]:
#her Vendor ucun ortalama ödəniş gecikməsi gunlerle
import pandas as pd
import sqlite3
query="""
SELECT v.VendorNumber,v.VendorName,round(AVG(JULIANDAY(v.PayDate) - JULIANDAY(v.InvoiceDate)),0) AS Avg_Payment_Delay
FROM vendor_invoice v
JOIN purchases p USING (VendorNumber)
GROUP BY v.VendorNumber, v.VendorName
ORDER BY Avg_Payment_Delay DESC;
"""
pd.read_sql(query,conn)

     VendorNumber                   VendorName  Avg_Payment_Delay
0              54  Aaper Alcohol & Chemical Co               43.0
1            4901          Laureate Imports Co               41.0
2            3551  Gilmanton Winery & Vineyard               40.0
3            6280                     Uncorked               40.0
4            9751           Vinedrea Wines Llc               39.0
..            ...                          ...                ...
123          1439       Capstone International               31.0
124          9099                 Truett Hurst               31.0
125         90026       Silver Mountain Ciders               31.0
126          5083             Loyal Dog Winery               29.0
127         90033      Fantasy Fine Wines Corp               29.0

[128 rows x 3 columns]